name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE.txt
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE.txt
      - README.md

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Clippy
      run: cargo clippy -- -Dwarnings -Wclippy::all
  upload-artifact:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # No need to upload artifacts on branches other than main
    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      name: Upload artifact
      with:
        name: stickyvar-${{ matrix.os }}
        path: |
          target/release/stickyvar
          target/release/stickyvar.exe
        retention-days: 90
