name: Build and upload artifacts

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v4
      name: Upload artifact
      with:
        name: stickyvar-${{ matrix.os }}
        path: |
          target/release/stickyvar
          target/release/stickyvar.exe
        retention-days: 90
